eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
                       url(r'^$', 'home', name='home'),
)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
                       url(r'^$', 'subscribe', name='subscribe'),
                       url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('eventex.core.urls', namespace='core')),
)

eventex/subscriptions/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('nome'),max_length=100)
    cpf = models.CharField(_('CPF'),max_length=11, unique=True)
    email = models.EmailField(_('e-mail'),blank=True)
    phone = models.CharField(_('telefone'),max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'),auto_now_add=True)
    paid = models.BooleanField(_('Pago'), default=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições')

eventex/subscriptions/forms.py
# coding: utf-8

from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from eventex.subscriptions.models import Subscription

def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas números'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 dígitos'))

class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (
            forms.TextInput(attrs=attrs),
            forms.TextInput(attrs=attrs))
        super(PhoneWidget, self).__init__(widgets,attrs)

    def decompress(self, value):
        if not value:
            return[None,None]
        return value.split('-')

class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (
            forms.IntegerField(),
            forms.IntegerField()
        )
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Número inválido'))
        return '%s-%s' % tuple(data_list)

class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)

    class Meta:
        model = Subscription
        exclude = ('paid',)

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)
        self.fields['cpf'].validators.append(CPFValidator)

    def clean_name(self):
        name = self.cleaned_data['name']
        words = map(lambda w: w.capitalize(), name.split())
        #words = name.split()
        #for index, word in enumerate(words):
        #    words[index] = word.capitalize()
        capitalized_name = ' '.join(words)
        return capitalized_name

    def clean(self):
        super(SubscriptionForm, self).clean()

        if not self.cleaned_data['email'] and \
          not self.cleaned_data['phone']:
            raise ValidationError(_(u'Informe seu email ou telefone'))

        return self.cleaned_data

eventex/core/views.py
# coding: utf-8

from django.shortcuts import render_to_response, render
from django.template import RequestContext
from django.conf import settings

def home(request):
    return render(request, 'core/index.html')

eventex/subscriptions/views.py
from django.shortcuts import render
from django.http import (HttpResponseRedirect, HttpResponse)
from django.shortcuts import get_object_or_404
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)

def new(request):
    return render(request, 'subscriptions/subscription_form.html',
        {'form':SubscriptionForm()})

def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html',
            {'form':form})

    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)

def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request, 'subscriptions/subscription_detail.html', {'subscription':subscription})

eventex/core/templates/core/index.html
{% extends 'base.html' %}
{% block content %}
    <!-- #page -->
        <!-- home content -->
        <section class="page_section parallax_effect" id="home" data-stellar-background-ratio="0.5" >
			
				<div class="container">
					<div class="welcome_block">
						<img src="{{ STATIC_URL }}img/emblem.png" alt="" />
						<h1>Eventex</h1>
						<p>O evento mais sensacional do ano.</p>
                        <p>Você não pode deixar de perder</p>
                        <iframe src="{% url 'subscriptions:subscribe' %}" width="600" height="200" frameborder="0" marginheight="0" marginwidth="0">
                            Carregando...
                        </iframe>
					</div>
					<a href="#about" class="down_btn"></a>
				</div>
			
			<div class="home_gradient"></div>
        </section>       

        <!-- about content-->
        <section class="page_section" id="about">
            <!-- section header -->
			<div class="container">
				<h2><span>Sobre</span></h2>
			</div>
            <!-- //section header -->
            
            <!-- section content -->
            <div class="content_section container"> 
                <div class="row">
                	<div class="span6">
						<p>Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin congue orci sed aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum, elit ac fermentum egestas, tortor ante vestibulum est, eget scelerisque nisl velit eget tellus. Fusce porta facilisis luctus.</p>
						<p>Integer neque dolor, rhoncus nec euismod eget, pharetra et tortor. Nulla id pulvinar nunc. Vestibulum auctor nisl vel lectus ullamcorper sed pellentesque dolor eleifend. Praesent lobortis magna vel diam mattis sagittis.</p>
						<ul class="spsk">
							<li class="icon1">Cras sagittis commodo risus, et sollicitudin lacus ultrices quis.</li>
							<li class="icon2">Fusce cursus ipsum id felis dictum at interdum sapien bibendum.</li>
							<li class="icon3">Integer vitae molestie eros.</li>
							<li class="icon4">Nam luctus, ipsum in volutpat commodo, tortor erat</li>
						</ul>
					</div>
                    <div class="span6"><img src="{{ STATIC_URL }}img/evento.jpg" alt="" /></div>
					<div class="clear"></div>
                </div>
                <div class="row services_block">
                </div>
            </div>
            <!-- //section content -->
        </section>


        <!-- events content-->
        <section class="page_section" id="events">
            <!-- section header -->
			<div class="container">
				<h2><span>Eventos</span></h2>
			</div><!-- //section header -->
            
            <!-- section content -->
            <div class="content_section container"> 
                <div class="row events_block projects">
					<div class="element span6">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/1.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/1.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Eventex 2014</a>
								<div class="event_info"><span class="fleft">August 8, 2014</span><span class="fright">Rio de Janeiro</span><div class="clear"></div></div>
								O evento terá a participação especial de Henrique Bastos, o nosso Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ele abordará o tema Morbi rutrum, elit ac fermentum <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span6">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/2.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/2.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Etiam nec turpis et risus</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin congue orci sed aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum, elit ac fermentum <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span6">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/3.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/3.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Suspendisse fringilla a massa</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin congue orci sed aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum, elit ac fermentum <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span3">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/4.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/4.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Morbi ut mattis</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span3">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/5.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/5.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Nulla eget venatis</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span5">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/6.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/6.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Vivamus id faucibus enim</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin congue orci sed aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span4">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/7.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/7.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Proin egestas nunc libero</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="element span3">
						<div class="event_item">
							<div class="event_img">
								<img src="{{ STATIC_URL }}img/events/8.jpg" alt="" />
								<a class="zoom" href="{{ STATIC_URL }}img/events/8.jpg" rel="prettyPhoto[portfolio1]"></a>
							</div>
							<div class="event_description">
								<a class="title" href="javascript:void(0);" alt="">Fusce quis sapien</a>
								<div class="event_info"><span class="fleft">August 8, 2020</span><span class="fright">London</span><div class="clear"></div></div>
								Aenean sagittis tortor quis nisl aliquet at rutrum nisi posuere. Ut sollicitudin <a class="read_more" href="javascript:void(0);" alt="">[...]</a>
							</div>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</div><!-- //section content -->
        </section>
		
		<section id="testimonials">
            <!-- section header -->
			<div class="parallax_effect" data-stellar-background-ratio="0.5">
				<div class="container">
					<div class="testimonials_block">
						<div class="testimonials_txt">Fusce ornare semper varius. Duis ac mi neque. Praesent vitae eros urna. Integer dapibus, tellus non laoreet gravida, neque turpis ultricies tellus, a ullamcorper ipsum eros a lacus. Donec lectus turpis, viverra lobortis suscipit vitae, aliquet id diam. Mauris aliquam, neque mollis convallis tempor, lacus mauris adipiscing arcu, quis porttitor magna sapien a dui. Quisque eu neque nulla. Fusce dictum diam id felis vestibulum a sollicitudin ligula vestibulum. Integer vel mattis sem. Morbi ut enim id nunc pulvinar iaculis.</div>
						<a href="javascript:void(0);"><img src="{{ STATIC_URL }}img/avatar1.jpg" alt="" /></a>
						<div class="author_inf"><span>Chuck Norris,</span>o cara</div>
					</div>
				</div><!-- end .container -->
				<div class="home_gradient"></div>
			</div><!-- //section header -->
		</section>

        <!-- Contact content -->
        <section class="page_section" id="contact">
            <!-- section header -->
            <div class="container">
				<h2><span>Contatos</span></h2>
			</div><!-- //section header -->
                        
            <!-- section content -->
            <div class="content_section container">
                <div class="row">
					<div class="span12">
                    	<p>Sed sit amet lectus id libero sagittis mollis vel in sem. Quisque eu tempus neque, at ultricies turpis. Fusce nec leo quis quam ultrices commodo id eget ante. Sed tincidunt metus eu magna ultrices, at lobortis magna elementum.</p>
                    </div>
					<div class="clear"></div>
                	<div class="span3 contact_info">
                    	<h3>London</h3>
						<p>Chuck Norris</br>Não o procure</br>Ele vai até você</br>London NW1</p>
						<span>Email :</span><a href="mailto:chucknorris@sitename.com" alt="">chucknorris@sitename.com</a></br>
						<span>Phone :</span>+1 959 603 6035
                	</div>
					<div class="span3 contact_info">
                    	<h3>New York</h3>
						<p>Chuck Norris</br>Não o procure</br>Ele vai até você</br>New York NY 1</p>
						<span>Email :</span><a href="mailto:chucknorris@sitename.com" alt="">chucknorris@sitename.com</a></br>
						<span>Phone :</span>+1 959 734 8569
                	</div>
					<div class="span3 contact_info">
                    	<h3>Brooklyn</h3>
						<p>Chuck Norris</br>Não o procure</br>Ele vai até você</br>Brooklyn</p>
						<span>Email :</span><a href="mailto:chucknorris@sitename.com" alt="">chucknorris@sitename.com</a></br>
						<span>Phone :</span>+1 959 478 3457
                	</div>
					<div class="span3 contact_info">
                    	<h3>Miami</h3>
						<p>Chuck Norris</br>Não o procure</br>Ele vai até você</br>Miami</p>
						<span>Email :</span><a href="mailto:chucknorris@sitename.com" alt="">chucknorris@sitename.com</a></br>
						<span>Phone :</span>+1 959 603 6035
                	</div>
					<div class="clear"></div>
                </div>
                <div class="row map">
                    <div class="span12">
                        <img src="{{ STATIC_URL }}img/mapa.jpg" width="1020" />
                    </div>
                </div>
            </div>
                  
            <!-- //section content -->
        </section>
        <!--footer-->
        <div class="footer">
        	<!-- footer_bottom -->
        	<div class="footer_bottom container">         
                <div class="fleft copyright">Eventex &copy; 2020 | <a href="javascript:void(0);">Privacy Policy</a></div>
				<a href="#home" class="fright down_btn">Início</a>
				<div class="clear"></div>
            </div>
        	<!-- //footer_bottom -->
        </div>
        <!--//footer-->
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>Parabéns, {{ subscription.name }}</p>
    <p>Sua inscrição foi realizada em {{ subscription.created_at|date:"d/m/Y" }}</p>
    <p>Em breve entraremos em contato pelo
        {% if subscription.phone %}
            telefone {{ subscription.phone }}
        {% else %}
            email {{ subscription.email }}
        {% endif %}
    </p>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% block content %}
<form action="." method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <p>
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
        {{ form.name }}
        {{ form.name.errors }}
    </p>
    <p>
        <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
        {{ form.cpf }}
        {{ form.cpf.errors }}
    </p>
    <p>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
        {{ form.email }}
        {{ form.email.errors }}
    </p>
    <p>
        <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
        {{ form.phone }}
        {{ form.phone.errors }}
    </p>
    <input type="submit" value="Enviar" class="button">
</form>
{% endblock content %}